const ACTION_CARDS_ENABLED = true;
const STARTING_CARD_ACTION_ALLOWED = false;
const PLAYER_KNOCKING_ENABLED = false;

module.exports = {
  STARTING_CARD_ACTION_ALLOWED,
  ACTION_CARDS_ENABLED,
  PLAYER_KNOCKING_ENABLED
};
